# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Addon by Ed Asriyan
version: "9.0"
slug: example
description: The example add-on for Home Assistant.
url: "https://github.com/ed-asriyan/test-app"
arch:
  - aarch64
  - amd64
init: false
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/ed-asriyan/{arch}-test-app"
